FROM python:3-alpine

WORKDIR /bot

COPY requirements.txt /bot

VOLUME [ "/bot" ]

RUN apk update && apk add python3-dev \
                        gcc \
                        libc-dev
RUN pip3 install -r requirements.txt

CMD python bot.py
